# Ansible playbook to install software into the media server
---
- name: Server Deployment Playbook
  hosts: "{{ myhosts | default('all') }}" # read from cli or all hosts
  vars:
    # NOTE: ~/.bashrc does not work in non-interactive mode on Ubuntu 24.04
    # might need to manually source this in shell block as well;
    config_file: "/etc/profile.d/media-server-env.sh"
    install_dir: "/usr/local/bin"
    apps_dir: "/home/{{ ansible_user }}/apps"
    apps_config_dir: "/home/{{ ansible_user }}/apps/config" # make sure this matches templates/.env
    smb_group: sharing
    smb_user: "{{ ansible_user }}"
    sharing_user: shareuser
    media_mountpoint: "/mnt/media"
    apps_mountpoint: "/mnt/apps" # APP_DIR
    scratch_mountpoint: "/mnt/scratch" # SCRATCH_DIR
    scripts_dir: "/home/{{ ansible_user }}/scripts"
  tasks:
  # INITIAL SETUP
  - name: get Ubuntu codename
    shell: . /etc/os-release && echo "$VERSION_CODENAME"
    register: ubuntu_codename

  - name: get Ubuntu release
    shell: uname -r
    register: ubuntu_release

  - name: Create config file
    become: true
    file:
      path: "{{ config_file }}"
      state: touch

  # RUN TASK SETS
  - include_tasks: tasks/apt_install_base.yaml
  - include_tasks: tasks/docker.yaml
  - include_tasks: tasks/mergerfs.yaml
  - include_tasks: tasks/snapraid.yaml
  - include_tasks: tasks/nvidia_cuda.yaml
  - include_tasks: tasks/nvidia_ctk.yaml
  - include_tasks: tasks/nvidia_drivers.yaml
  - include_tasks: tasks/intel_drivers.yaml
  - include_tasks: tasks/ffmpeg_container.yaml # TODO: fix this
  - include_tasks: tasks/disk_setup.yaml
  - include_tasks: tasks/samba.yaml
  - include_tasks: tasks/phoronix.yaml
  - include_tasks: tasks/smartd.yaml
  - include_tasks: tasks/apps.yaml
  - include_tasks: tasks/scripts.yaml




