---
- name: Set up media apps dir
  file:
    path: "{{ apps_dir }}"
    state: directory

- name: Set up media apps config dir
  file:
    path: "{{ apps_config_dir }}"
    state: directory

# Plex gets its own directory
- name: Set up Plex app dir
  file:
    path: "{{ apps_dir }}/plex"
    state: directory

- name: Add Plex docker compose templates
  template:
    src: "apps/{{ item }}"
    dest: "{{ apps_dir }}/plex/{{ item }}"
    force: false # do no overwrite existing
  loop:
    - ".env"
    - "plex.yaml"

- name: Add Plex docker compose file
  template:
    src: "apps/docker-compose-plex.yaml"
    dest: "{{ apps_dir }}/plex/docker-compose.yaml"

# all the rest of the services can share a dir
# NOTE: docker compose in the same dir are on the same docker network
- name: Add app services dir
  file:
    path: "{{ apps_dir }}/services"
    state: directory

- name: Add app services config dirs
  file:
    path: "{{ apps_config_dir }}/{{ item }}"
    state: directory
  loop:
    - "bazarr"
    - "sonarr"
    - "lidarr"
    - "radarr"
    - "prowlarr"
    - "scrutiny"
    - "tautulli"
    - "maintainerr"
    - ersatztv

- name: Add app services templates
  template:
    src: "apps/{{ item }}"
    dest: "{{ apps_dir }}/services/{{ item }}"
    force: false # do no overwrite existing
  loop:
    - ".env"
    - "docker-compose.yaml"
    - "bazarr.yaml"
    - "sonarr.yaml"
    - "lidarr.yaml"
    - "radarr.yaml"
    - "prowlarr.yaml"
    - "sabnzbd.yaml" # NOTE: this one saves config to APP_DIR
    - "scrutiny.yaml" # NOTE: this one saves config to APP_DIR and CONFIG_DIR
    - "tautulli.yaml"
    - "maintainerr.yaml"
    - ersatztv.yaml
