---
# NVIDIA DRIVERS
# https://docs.nvidia.com/datacenter/tesla/driver-installation-guide/index.html#ubuntu-installation
- name: Install Nvidia Driver
  become: true
  apt:
    update_cache: true
    pkg:
    - nvidia-driver-570

# NOTE: if you need to fix the drivers do this https://forums.developer.nvidia.com/t/how-to-fix-nvml-driver-library-version-mismatch-without-rebooting/269998