---
# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
- name: Check if Nvidia Container Toolkit is Set up
  stat:
    path: /etc/apt/sources.list.d/nvidia-container-toolkit.list
  register: nvctk_exists

- name: Setup Nvidia Container Toolkit
  shell: |
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
    && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  when: not nvctk_exists.stat.exists

- name: Install Nvidia Container Toolkit
  become: true
  apt:
    update_cache: true
    pkg:
    - nvidia-container-toolkit

- name: Make sure Docker daemon JSON exists
  become: true
  file:
    path: /etc/docker/daemon.json
    state: touch

- name: Check if we need to configure the Nvidia Container Toolkit
  # become: true
  lineinfile:
    # create: true
    path: /etc/docker/daemon.json
    regexp: ".*nvidia-container-runtime.*"
    state: absent
  check_mode: yes
  changed_when: false
  register: missing_ctk


- name: Configure Nvidia Container Toolkit
  shell: |
    sudo nvidia-ctk runtime configure --runtime=docker
    sudo systemctl restart docker
  when: not missing_ctk.found

  # NOTE: Test with:
  # sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi

  # NOTE: write this file:
  # $ cat /etc/docker/daemon.json
  # {
  #     "runtimes": {
  #         "nvidia": {
  #             "args": [],
  #             "path": "nvidia-container-runtime"
  #         }
  #     }
  # }