---
# INSTALL SNAPRAID
# https://github.com/amadvance/snapraid ; https://www.snapraid.it/download
- name: Check if SnapRAID installed
  stat:
    path: "{{ install_dir }}/snapraid"
  register: snapraid_exists

- name: Download SnapRAID
  become: true
  unarchive:
    src: https://github.com/amadvance/snapraid/releases/download/v12.4/snapraid-12.4.tar.gz
    dest: "{{ install_dir }}"
    remote_src: true
  when: not snapraid_exists.stat.exists


- name: Install SnapRAID
  shell: |
    cd "{{ install_dir }}/snapraid-12.4" && ./configure && make
  when: not snapraid_exists.stat.exists

- name: Symlink SnapRAID
  become: true
  file:
    src: "{{ install_dir }}/snapraid-12.4/snapraid"
    dest: "{{ install_dir }}/snapraid"
    state: link

- name: Update SnapRAID Conf
  become: true
  blockinfile:
    create: true
    backup: true
    marker: '# {mark} ANSIBLE MANAGED BLOCK FOR SnapRAID conf'
    path: "/etc/snapraid.conf"
    block: |
      parity /mnt/snapraid1/snapraid.parity
      2-parity /mnt/snapraid2/snapraid.2-parity
      content /var/snapraid/snapraid.content
      content /mnt/disk1/snapraid.content
      content /mnt/disk2/snapraid.content
      content /mnt/disk3/snapraid.content
      content /mnt/disk4/snapraid.content
      content /mnt/disk5/snapraid.content
      content /mnt/disk6/snapraid.content
      content /mnt/disk7/snapraid.content
      content /mnt/disk8/snapraid.content

      data d1 /mnt/disk1/
      data d2 /mnt/disk2/
      data d3 /mnt/disk3/
      data d4 /mnt/disk4/
      data d5 /mnt/disk5/
      data d6 /mnt/disk6/
      data d7 /mnt/disk7/
      data d8 /mnt/disk8/
      data d9 /mnt/disk9/

      # Excludes hidden files and directories
      exclude *.unrecoverable
      exclude /tmp/
      exclude /lost+found/
      exclude downloads/
      exclude Downloads/
      exclude appdata/
      exclude *.!sync
      exclude *.unrecoverable
      exclude /tmp/
      exclude /lost+found/
      exclude appdata/
      exclude .DS_Store
      exclude ._.DS_Store
      exclude .Thumbs.db
      exclude .fseventsd
      exclude .Spotlight-V100
      exclude .TemporaryItems
      exclude .Trashes
      exclude .nfo

- name: Create SnapRAID content dir on root
  become: true
  file:
    path: /var/snapraid
    owner: "{{ ansible_user }}"