# sudo ufw allow 9696
---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - $CONFIG_DIR/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped