---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - $CONFIG_DIR/lidarr:/config
      - $MEDIA_DIR:$MEDIA_DIR
    ports:
      - 8686:8686
    restart: unless-stopped