services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      # TODO: review if this should be in CONFIG_DIR or APP_DIR based on disk usage
      - $CONFIG_DIR/tautulli:/config
      # get the plex server's logs from local disk
      - $APP_DIR/plex/Library/Application Support/Plex Media Server/Logs:/plexmediaserver-logs:ro
    ports:
      - 8181:8181
    restart: unless-stopped